version: '3.8'
#Define docker services
services:
  #Docker image for Server App linked to local files (don't loose nodemon hot reload)
  server:
    image: server
    ports:
      - '3000:3000'
    build:
      context: ./server
    volumes:
      - ./server:/usr/src
    networks:
      - app-tmt
    depends_on:
      - mongo
  #Docker image for server MongoDB
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    networks:
      - app-tmt
    volumes:
      - mongo-data:/data/db
  #Docker image for Client App linked to local files (don't loose vite hot reload)
  client:
    image: client
    ports:
      - '3001:3001'
    build:
      context: ./client
    volumes:
      - ./client:/usr/src
    networks:
      - app-tmt
networks:
  app-tmt:
    driver: bridge
volumes:
  mongo-data:
    driver: local
